server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
    max-threads: 2000
    max-http-post-size: 30MB
    max-connections: 20000
    accept-count: 1000
    min-spare-threads: 50

spring:
  datasource:
    url: jdbc:mysql://192.168.3.128:3306/springboot?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: valarchieroot
    driver-class-name: com.mysql.cj.jdbc.Driver
# 采用alibaba druid连接池 http://localhost:8080/druid/sql.html 访问druid
    type: com.alibaba.druid.pool.DruidDataSource
# 下面为连接池的补充设置，应用到上面所有数据源中
# 初始化大小，最小，最大
    initial-size: 5
    min-idle: 5
    max-active: 20
# 配置获取连接等待超时的时间
    max-wait: 60000
# 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 60000
# 配置一个连接在池中最小生存的时间，单位是毫秒
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
# 打开PSCache，并且指定每个连接上PSCache的大小
    pool-prepared-statements: true
# 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat,wall
    use-global-data-source-stat: true
# 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

  redis:
    database: 0
    host: 192.168.3.129
    port: 6379
    password: valarchieroot
    #    jedis:
    lettuce:
      pool:
        # 连接池中的最大空闲连接 默认8
        max-idle: 8
        # 连接池中的最小空闲连接 默认0
        min-idle: 2
        # 连接池最大连接数 默认8 ，负数表示没有限制
        max-active: 16
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
        max-wait: -1
    timeout: 30000


  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true


  cache:
    cache-names: user
    type: caffeine
    caffeine:
      spec: initialCapacity=1000,maximumSize=10000,expireAfterWrite=5s

# 上传文件配置
  servlet:
    multipart:
      enabled: true
      max-file-size: 30MB
      max-request-size: 100MB

# 文件上传路径
file:
  upload-folder: upload/

# 加密属性
project:
  security:
    password: ENC(O2iZ3t7a36c5qASsBvXh+JzOZjl0pTCR)

# 配置加密的密码
# -Djasypt.encryptor.password=valarchie
# jasypt:
#   encryptor:
#     password: valarchie


# 日志配置
logging:
  config: classpath:logback-spring.xml
  level:
    root: debug

mybatis-plus:
  mapper-locations: classpath:com/valarchie/quickboot/infrastructure/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  如果文件在resource目录下的话
#  mapper-locations: classpath:/mapper/*.xml
#  type-aliases-package: com.wang.mapper.mysql








